let songs = [
    {
        id : 'wd',
        name : 'Wildest Dreams',
        path : 'music/nen/Wildest-Dreams.mp3',
        album : 'Nineteen-Eighty-Nine',
        cover : 'images/nen.jpeg',
        liked : 0,
    },
    {
        id : 'wh',
        name : 'White Horse',
        path : 'music/fearless/white-horse.mp3',
        album : 'Fearless',
        cover : 'images/fearless.jpeg',
        liked : 0,
    },
    {
        id : 'en',
        name : 'Enchanted',
        path : 'music/speak/Enchanted.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'run',
        name : 'Run',
        path : 'music/red/run.mp3',
        album : 'Red',
        cover : 'images/red.jpeg',
        liked : 0,
    },
    {
        id : 'ikp',
        name : 'I Know Places',
        path : 'music/nen/I-Know-Places.mp3',
        album : 'Nineteen-Eighty-Nine',
        cover : 'images/nen.jpeg',
        liked : 0,
    },
    {
        id : 'delicate',
        name : 'Delicate',
        path : 'music/rep/Delicate.mp3',
        album : 'Reputation',
        cover : 'images/reputation.jpeg',
        liked : 0,
    },
    {
        id : 'iftye',
        name : 'I Forgot That You Existed',
        path : 'music/lover/I-Forgot-That-You-Existed.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
    {
        id : 'peace',
        name : 'Peace',
        path : 'music/folk/peace.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'sn',
        name : 'Speak Now',
        path : 'music/speak/Speak-Now.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'hap',
        name : 'Happiness',
        path : 'music/ever/happiness.mp3',
        album : 'Evermore',
        cover : 'images/evermore.jpeg',
        liked : 0,
    },
    {
        id : 'okid',
        name : 'You\'re On Your Own Kid',
        path : 'music/mid/You\'re-On-Your-Own-Kid.mp3',
        album : 'Midnights',
        cover : 'images/midnights.jpeg',
        liked : 0,
    },
]