let songs = [
    {
        id : 'bttths',
        name : 'Bigger Than the Whole Sky',
        path : 'music_sad/bigger-than-the-whole-sky.mp3',
        album : 'Midnights',
        cover : 'images/midnights.jpeg',
        liked : 0,
    },
    {
        id : 'tl',
        name : 'The Lakes',
        path : 'music_sad/the-lakes.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'atw',
        name : 'All Too Well',
        path : 'music_sad/all-too-well.mp3',
        album : 'Red',
        cover : 'images/red.jpeg',
        liked : 0,
    },
    {
        id : 'btd',
        name : 'Back to December',
        path : 'music_sad/back-to-december.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'ci',
        name : 'Coney Island',
        path : 'music_sad/coney-island.mp3',
        album : 'Evermore',
        cover : 'images/evermore.jpeg',
        liked : 0,
    },
    {
        id : 'dj',
        name : 'Dear John',
        path : 'music_sad/dear-john.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'mtr',
        name : 'My Tears Ricochet',
        path : 'music_sad/my-tears-ricochet.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'sbt',
        name : 'Sad Beautiful Tragic',
        path : 'music_sad/sad-beautiful-tragic.mp3',
        album : 'Red',
        cover : 'images/red.jpeg',
        liked : 0,
    },
    {
        id : 'sygb',
        name : 'Soon You\'ll Get Better',
        path : 'music_sad/soon-youll-get-better.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
    {
        id : 'tmt',
        name : 'This is Me Trying',
        path : 'music_sad/this-is-me-trying.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'ta',
        name : 'The Archer',
        path : 'music_sad/the-archer.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
]