let songs = [
    {
        id : 'mad',
        name : 'Mad Woman',
        path : 'music_angry/mad-woman.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'babe',
        name : 'Babe',
        path : 'music_angry/babe.mp3',
        album : 'Red',
        cover : 'images/red.jpeg',
        liked : 0,
    },
    {
        id : 'blood',
        name : 'Bad Blood',
        path : 'music_angry/Bad-Blood.mp3',
        album : 'Nineteen-Eighty-Nine',
        cover : 'images/nen.jpeg',
        liked : 0,
    },
    {
        id : 'revenge',
        name : 'Better Than Revenge',
        path : 'music_angry/Better-Than-Revenge.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'change',
        name : 'Change',
        path : 'music_angry/change.mp3',
        album : 'Fearless',
        cover : 'images/fearless.jpeg',
        liked : 0,
    },
    {
        id : 'didBad',
        name : 'I Did Something Bad',
        path : 'music_angry/I-Did-Something-Bad.mp3',
        album : 'Reputation',
        cover : 'images/reputation.jpeg',
        liked : 0,
    },
    {
        id : 'karma',
        name : 'Karma',
        path : 'music_angry/Karma.mp3',
        album : 'Midnights',
        cover : 'images/midnights.jpeg',
        liked : 0,
    },
    {
        id : 'look',
        name : 'Look What You Made Me Do',
        path : 'music_angry/Look-What-You-Made-Me-Do.mp3',
        album : 'Reputation',
        cover : 'images/reputation.jpeg',
        liked : 0,
    },
    {
        id : 'man',
        name : 'The Man',
        path : 'music_angry/man.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
    {
        id : 'body',
        name : 'No Body No Criem',
        path : 'music_angry/no-body.mp3',
        album : 'Evermore',
        cover : 'images/evermore.jpeg',
        liked : 0,
    },
    {
        id : 'shit',
        name : 'Vigilante Shit',
        path : 'music_angry/Vigilante-Shit.mp3',
        album : 'Midnights',
        cover : 'images/midnights.jpeg',
        liked : 0,
    },
]