let songs = [
    {
        id : 'day',
        name : 'Daylight',
        path : 'music_happy/Daylight.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
    {
        id : 'bej',
        name : 'Bejeweled',
        path : 'music_happy/Bejeweled.mp3',
        album : 'Midnights',
        cover : 'images/midnights.jpeg',
        liked : 0,
    },
    {
        id : 'fear',
        name : 'Fearless',
        path : 'music_happy/fearless_song.mp3',
        album : 'Fearless',
        cover : 'images/fearless.jpeg',
        liked : 0,
    },
    {
        id : 'gorg',
        name : 'Gorgeous',
        path : 'music_happy/Gorgeous.mp3',
        album : 'Reputation',
        cover : 'images/reputation.jpeg',
        liked : 0,
    },
    {
        id : 'inv',
        name : 'Invisible String',
        path : 'music_happy/invisible-string.mp3',
        album : 'Folklore',
        cover : 'images/folklore.jpeg',
        liked : 0,
    },
    {
        id : 'live',
        name : 'Long Live',
        path : 'music_happy/long-live.mp3',
        album : 'Speak-Now',
        cover : 'images/Speak Now.jpeg',
        liked : 0,
    },
    {
        id : 'me',
        name : 'ME!',
        path : 'music_happy/ME.mp3',
        album : 'Lover',
        cover : 'images/lover.jpeg',
        liked : 0,
    },
    {
        id : 'msg',
        name : 'Message in a Bottle',
        path : 'music_happy/Message-In-A-Bottle.mp3',
        album : 'Red',
        cover : 'images/red.jpeg',
        liked : 0,
    },
    {
        id : 'shake',
        name : 'Shake It Off',
        path : 'music_happy/Shake-It-Off.mp3',
        album : 'Nineteen-Eighty-Nine',
        cover : 'images/nen.jpeg',
        liked : 0,
    },
    {
        id : 'willow',
        name : 'Willow',
        path : 'music_happy/willow.mp3',
        album : 'Evermore',
        cover : 'images/evermore.jpeg',
        liked : 0,
    },
    {
        id : 'belong',
        name : 'You Belong With Me',
        path : 'music_happy/you-belong-with-me.mp3',
        album : 'Fearless',
        cover : 'images/fearless.jpeg',
        liked : 0,
    },
]